name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm install
        - name: Build
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm run build
        - name: Test
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm run test
